name: HTML Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PROJECT_NAME: git-learning
  ENVIRONMENT: learning      

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .

      - name: Show variable & Secretes
        run: |
          echo "Project: $PROJECT_NAME"
          echo "Envionment: $ENVIRONMENT"
          echo "Secret exists: ${PRACTICE_SECRET:+yes}"
        env:
          PRACTICE_SECRET: ${{ secrets.PRACTICE_SECRET }}  
